### ISSUE TITLE
Attack/jump assignments are lablled the wrong way round in menu 

### ISSUE THREAD

**Issue by LordBarker80** [furrtek/Arcade-TMNT_MiSTer#12]
Example: mapping what is listed as 'attack' in the configuration menu to button 1 actually makes the turtle jump and vice versa.

**Comment by city41** [comment]
I am finding button mappings don't seem to work for me, using core TMNT_20230428.rbf.

- Service acts as Coin
- Attack acts as Start before a game has begun, then Jump once in game
- No button seems to be Attack once in game

I have one joystick attached to my Mister, and have not experienced this on any other core.

btw thanks for the awesome core!

**Comment by city41** [comment]
Missing In Action does seem to map the buttons correctly.

**Comment by city41** [comment]
And also here is what the buttons map to at the mister level when starting TMNT

![PXL_20230429_170914495](https://user-images.githubusercontent.com/141159/235315050-41fe92e7-ea8e-4740-bdde-c3d840dc18ad.jpg)
